### ISSUE TITLE
Handle errors from baron better

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#10]
I've seen an error via baron when running mutmut, which seems to display the
same exception twice, and provides no reference to the source:

```
% mutmut project --tests-dir project/app/tests
Traceback (most recent call last):
  File "…/project/.venv/lib/python3.6/site-packages/baron/baron.py", line 20, in _parse
    return parser(tokens)
  File "…/project/.venv/lib/python3.6/site-packages/baron/grammator.py", line 695, in parse
    return parser.parse(iter(tokens))
  File "…/project/.venv/lib/python3.6/site-packages/baron/parser.py", line 168, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token DOUBLE_STAR here:

1381 … 
1382 …            
1383 …
1384 …       
1385 …              
1386 …
1387 
1388         foo_kwargs = {**<---- here

The token DOUBLE_STAR should be one of those: BACKQUOTE, BINARY, BINARY_RAW_STRING, BINARY_STRING, COMPLEX, FLOAT, FLOAT_EXPONANT, FLOAT_EXPONANT_COMPLEX, HEXA, INT, LAMBDA, LEFT_BRACKET, LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LONG, MINUS, NAME, NOT, OCTA, PLUS, RAW_STRING, RIGHT_BRACKET, STRING, TILDE, UNICODE_RAW_STRING, UNICODE_STRING

It is not normal that you see this error, it means that Baron has failed to parse valid Python code. It would be kind if you can extract the snippet of your code that makes Baron fail and open a bug here: https://github.com/Psycojoker/baron/issues

Sorry for the inconvenience.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/project/.venv/bin/mutmut", line 5, in <module>
    main()
  File "…/project/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "…/project/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "…/project/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "…/project/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "…/project/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 35, in wrapper
    f(*args, **kwargs)
  File "…/project/.venv/lib/python3.6/site-packages/mutmut/__main__.py", line 135, in main
    mutations_by_file[filename] = count_mutations(open(filename).read(), context__filename=filename, context__exclude=exclude)
  File "…/project/.venv/lib/python3.6/site-packages/tri/declarative/__init__.py", line 587, in wrapper
    return f(*args, **setdefaults_path(Namespace(), kwargs, defaults))
  File "…/project/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 365, in count_mutations
    return mutate(source, ALL, context=context)[1]
  File "…/project/.venv/lib/python3.6/site-packages/tri/declarative/__init__.py", line 587, in wrapper
    return f(*args, **setdefaults_path(Namespace(), kwargs, defaults))
  File "…/project/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 282, in mutate
    result = parse(source)
  File "…/project/.venv/lib/python3.6/site-packages/baron/baron.py", line 66, in parse
    return _parse(tokens, print_function)
  File "…/project/.venv/lib/python3.6/site-packages/baron/baron.py", line 26, in _parse
    raise e
  File "…/project/.venv/lib/python3.6/site-packages/baron/baron.py", line 24, in _parse
    return parser(tokens)
  File "…/project/.venv/lib/python3.6/site-packages/baron/grammator.py", line 695, in parse
    return parser.parse(iter(tokens))
  File "…/project/.venv/lib/python3.6/site-packages/baron/parser.py", line 168, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token DOUBLE_STAR here:

1381 … 
1382 …            
1383 …
1384 …       
1385 …              
1386 …
1387 
1388         foo_kwargs = {**<---- here

The token DOUBLE_STAR should be one of those: BACKQUOTE, BINARY, BINARY_RAW_STRING, BINARY_STRING, COMPLEX, FLOAT, FLOAT_EXPONANT, FLOAT_EXPONANT_COMPLEX, HEXA, INT, LAMBDA, LEFT_BRACKET, LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LONG, MINUS, NAME, NOT, OCTA, PLUS, RAW_STRING, RIGHT_BRACKET, STRING, TILDE, UNICODE_RAW_STRING, UNICODE_STRING

It is not normal that you see this error, it means that Baron has failed to parse valid Python code. It would be kind if you can extract the snippet of your code that makes Baron fail and open a bug here: https://github.com/Psycojoker/baron/issues

Sorry for the inconvenience.

**Comment by blueyed** [comment]
baron also fails on type annotions, so it is a bit a bummer to rely on it currently..
I have not found an open issue regarding this, only the info from the readme that it targets Python 2.

**Comment by boxed** [comment]
There are open PRs in baron to fix most or all of Python 3 support and they are in the merging process right now. Hopefully this all gets sorted within a week or two! 

I agree though that mutmut should handle these types of errors better. Should be simple enough.
