### ISSUE TITLE
`mutmut show` on an invalid mutation id tracebacks

### ISSUE THREAD

**Issue by OddBloke** [boxed/mutmut#121]
```pytb
$ mutmut show 0
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/bin/mutmut", line 5, in <module>
    climain()
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/lib/python3.7/site-packages/mutmut/__main__.py", line 74, in wrapper
    f(*args, **kwargs)
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/lib/python3.7/site-packages/mutmut/__main__.py", line 254, in climain
    post_mutation, use_patch_file))
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/lib/python3.7/site-packages/mutmut/__main__.py", line 292, in main
    print(get_unified_diff(argument, dict_synonyms))
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/lib/python3.7/site-packages/mutmut/cache.py", line 171, in get_unified_diff
    filename, mutation_id = filename_and_mutation_id_from_pk(argument)
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/lib/python3.7/site-packages/mutmut/cache.py", line 105, in wrapper
    return f(*args, **kwargs)
  File "<string>", line 2, in filename_and_mutation_id_from_pk
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/lib/python3.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/home/daniel/.virtualenvs/ubuntu-advantage-client/lib/python3.7/site-packages/mutmut/cache.py", line 335, in filename_and_mutation_id_from_pk
    return mutant.line.sourcefile.filename, mutation_id_from_pk(pk)
AttributeError: 'NoneType' object has no attribute 'line'
```

I would expect a more friendly error message.

**Comment by boxed** [comment]
Agreed.

**Comment by OddBloke** [comment]
Thanks!
