### ISSUE TITLE
UnicodeDecodeError running mutmut on Windows

### ISSUE THREAD

**Issue by reebr** [boxed/mutmut#133]
Hello.
I'm getting the following error when try to run mutmut:

```
PS C:\Users\renan\Desktop\development\drivote-api> mutmut --paths-to-mutate=drivote run

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
� Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
� Suspicious.       Tests took a long time, but not long enough to be fatal.
� Survived.         This means your tests needs to be expanded.

mutmut cache is out of date, clearing it...
1. Running tests without mutations
⠋ Running... Done

2. Checking mutants
⠼ 137/299  � 85  ⏰ 0  � 0  � 52Traceback (most recent call last):
  File "c:\users\renan\.virtualenvs\drivote-api-szzd2ndc\lib\site-packages\mutmut\__main__.py", line 432, in main
    run_mutation_tests(config=config, mutations_by_file=mutations_by_file)
  File "c:\users\renan\.virtualenvs\drivote-api-szzd2ndc\lib\site-packages\mutmut\__main__.py", line 630, in run_mutation_tests
    run_mutation_tests_for_file(config, file_to_mutate, mutations)
  File "c:\users\renan\.virtualenvs\drivote-api-szzd2ndc\lib\site-packages\mutmut\__main__.py", line 616, in run_mutation_tests_for_file
    status = run_mutation(config, file_to_mutate, mutation_id)
  File "c:\users\renan\.virtualenvs\drivote-api-szzd2ndc\lib\site-packages\mutmut\__main__.py", line 584, in run_mutation
    survived = tests_pass(config)
  File "c:\users\renan\.virtualenvs\drivote-api-szzd2ndc\lib\site-packages\mutmut\__main__.py", line 534, in tests_pass
    returncode = popen_streaming_output(config.test_command, feedback, timeout=config.baseline_time_elapsed * 10)
  File "c:\users\renan\.virtualenvs\drivote-api-szzd2ndc\lib\site-packages\mutmut\__main__.py", line 496, in popen_streaming_output
    line = line.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 31: invalid continuation byte
```

Is there any flag to run in verbose mode or any alternative to find out in which file this flaw is happening?

Env:
- Python 3.7.3
- Windows 10 Pro

**Comment by boxed** [comment]
You can just walk the filesystem and try opening them in utf8:

```python
from pathlib import Path
for p in Path('drivote').glob('**/*.py'):
    print(f)
    with open(p) as f:
        f.read().decode('utf8')
```

Seems like you have some files that have some bad encoding in them. You should only have utf8.

**Comment by boxed** [comment]
I'm closing this due to lack of feedback.
