### ISSUE TITLE
Failed to run on code from https://github.com/m4r35n357/ODE-Playground

### ISSUE THREAD

**Issue by m4r35n357** [boxed/mutmut#139]
code hash is tag 4.13

```
$ mutmut --paths-to-mutate ad.py run

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests needs to be expanded.

mutmut cache is out of date, clearing it...
1. Running tests without mutations
⠇ Running... Done
Failed to parse ad.py. Internal error from parso follows.
----------------------------------
Traceback (most recent call last):
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/parser.py", line 178, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: TokenType(FSTRING_STRING)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/mutmut/__main__.py", line 726, in add_mutations_by_file
    mutations_by_file[filename] = list_mutations(context)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/mutmut/__init__.py", line 594, in list_mutations
    mutate(context)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/mutmut/__init__.py", line 478, in mutate
    result = parse(context.source, error_recovery=False)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/__init__.py", line 58, in parse
    return grammar.parse(code, **kwargs)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/grammar.py", line 141, in _parse
    root_node = p.parse(tokens=tokens)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/python/parser.py", line 82, in parse
    return super(Parser, self).parse(tokens)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/parser.py", line 128, in parse
    self._add_token(token)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/parser.py", line 184, in _add_token
    self.error_recovery(token)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/python/parser.py", line 147, in error_recovery
    return super(Parser, self).error_recovery(token)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/parso/parser.py", line 151, in error_recovery
    raise ParserSyntaxError('SyntaxError: invalid syntax', error_leaf)
parso.parser.ParserSyntaxError: ('SyntaxError: invalid syntax', <ErrorLeaf: TokenType(FSTRING_STRING):'self.der:+.', (209, 49)>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ian/.virtualenvs/gmpy2/bin/mutmut", line 10, in <module>
    sys.exit(climain())
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/mutmut/__main__.py", line 75, in wrapper
    f(*args, **kwargs)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/mutmut/__main__.py", line 256, in climain
    post_mutation, use_patch_file, paths_to_exclude))
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/mutmut/__main__.py", line 404, in main
    add_mutations_by_file(mutations_by_file, filename, _exclude, dict_synonyms)
  File "/home/ian/.virtualenvs/gmpy2/lib/python3.7/site-packages/mutmut/__main__.py", line 729, in add_mutations_by_file
    raise RuntimeError('Failed while creating mutations for %s, for line "%s"' % (context.filename, context.current_source_line), e)
RuntimeError: ('Failed while creating mutations for ad.py, for line "#"', ParserSyntaxError('SyntaxError: invalid syntax', <ErrorLeaf: TokenType(FSTRING_STRING):'self.der:+.', (209, 49)>))
```

**Comment by boxed** [comment]
Strange. I tried this exact command and with 4.13 of that repo, but I can't reproduce the crash. Maybe you have an old version of parso that doesn't support fancy f-strings? Can you run `pip freeze | grep parso` to see which version you have?

**Comment by m4r35n357** [comment]
OK I will re-investigate today, thanks for replying.

**Comment by m4r35n357** [comment]
`$ pip freeze | grep parso
parso==0.3.1
`

**Comment by boxed** [comment]
I had 0.4 locally when I first tried and could upgrade to 0.5. Mutmut has 0.4 in the requirements so you should have gotten an old version like that.

**Comment by m4r35n357** [comment]
Upgraded parso (now 0.5.1) and mutmut is now running, thanks!  Don't know how I got the old version, maybe I already had it and the requirements didn't update it for some reason?

**Comment by boxed** [comment]
Maybe. Good to see it working now though! Hope you get some value from it.

**Comment by m4r35n357** [comment]
Just to let you know, I am using it right now, and have already improved my tests, thanks!
