### ISSUE TITLE
Weird UnicodeDecodeError

### ISSUE THREAD

**Issue by Themanwithoutaplan** [boxed/mutmut#164]
Just started with MutMut and got this error:

```
Traceback (most recent call last):
  File "/Users/charlieclark/temp/op/bin/mutmut", line 8, in <module>
    sys.exit(climain())
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/mutmut/__main__.py", line 50, in wrapper
    f(*args, **kwargs)
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/mutmut/__main__.py", line 230, in climain
    post_mutation, use_patch_file, paths_to_exclude))
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/mutmut/__main__.py", line 382, in main
    update_line_numbers(filename)
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/mutmut/cache.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "<string>", line 2, in update_line_numbers
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/Users/charlieclark/temp/op/lib/python3.7/site-packages/mutmut/cache.py", line 242, in update_line_numbers
    existing_lines = [x.strip('\n') for x in f.readlines()]
  File "/Users/charlieclark/temp/op/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4786: invalid start byte
```
No indication where this is coming from but going between bytes and unicode is common in my library.

**Comment by boxed** [comment]
That's not it. You have a source file that isn't valid utf8.

**Comment by Themanwithoutaplan** [comment]
Any pointers on how I can find the file? I seemed to have more success when I explicitly set the path to search.

**Comment by boxed** [comment]
```python
from os import walk
from os.path import join

for r, d, fs in walk('.'):
    for f in fs:
        if not f.endswith('.py'):
            continue
        full = join(r, f)
        print(full)
        with open(full, encoding='utf8') as foo:
            foo.read()
```

**Comment by Themanwithoutaplan** [comment]
Thanks, haven't used `os.walk` in longer than I care to remember!

This is the actual culprit: `./lib/python3.7/site-packages/pony/converting.py` (I'm running in a virtualenv) so not related to my own library. Note that this file has an explicit cp1251 declaration at the start which is valid Python. In fact, I think reading with an explicit conversion from utf-8 is probably wrong.

As noted above, I can work around this with an explicit `--paths-to-mutate` directive. I have `norecursedirs` set for pytest maybe this should be picked up by mutmut?

PS. 32,567 mutants in total, which will take a few days to run. Maybe there should be some kind of indication after the first scan?

**Comment by boxed** [comment]
Yes it's wrong to only support utf8, but it's also crazy to have anything else and extremely uncommon. 

The problem in your case is that you've put your virtualenv in a place mutmut auto detects as your own source code. Mumut should never read the virtualenv code! You need to explicitly tell mutmut where your code is.

**Comment by jeffwright13** [comment]
I also ran into this, and I also use a virtualenv. Perhaps the default behavior should be to not examine commonly used virtualenv directories, like `venv` or `.venv`?

I'd also like to add a +1 to the suggestion of having a time-based indicator for completion. The spinner is nice, but I know some spinner libraries give you the ability to estimate time left.

**Comment by boxed** [comment]
Mutmut shouldn't even enumerate the venv anyway. What is your directory structure?

**Comment by jeffwright13** [comment]
It is a venv and a single test file.
```
~/coding/mutmut ⌚ 15:30:42
$ ls -la
total 184
drwxr-xr-x   7 jwr003  542971493    224 Jun 30 15:16 .
drwxr-xr-x  71 jwr003  542971493   2272 Jun 29 10:36 ..
-rw-r--r--   1 jwr003  542971493  53248 Jun 30 15:16 .coverage
-rw-r--r--   1 jwr003  542971493  36864 Jun 29 11:13 .mutmut-cache
drwxr-xr-x   6 jwr003  542971493    192 Jun 29 10:43 .pytest_cache
-rw-r--r--   1 jwr003  542971493    275 Jun 29 11:13 test_lt_gt.py
drwxr-xr-x   6 jwr003  542971493    192 Jun 29 10:37 venv
```

**Comment by jeffwright13** [comment]
Here is the error I get (same as OP):
```
~/coding/mutmut ⌚ 15:35:22
$ mutmut run --paths-to-mutate .

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests need to be expanded.
🔇 Skipped.          Skipped.

1. Using cached time for baseline tests, to run baseline again delete the cache file
Traceback (most recent call last):
  File "/Users/jwr003/coding/mutmut/venv/bin/mutmut", line 8, in <module>
    sys.exit(climain())
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/mutmut/__init__.py", line 882, in wrapper
    f(*args, **kwargs)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/mutmut/__main__.py", line 142, in run
    sys.exit(do_run(argument, paths_to_mutate, disable_mutation_types, enable_mutation_types, runner,
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/mutmut/__main__.py", line 397, in do_run
    parse_run_argument(argument, config, dict_synonyms, mutations_by_file, paths_to_exclude, paths_to_mutate, tests_dirs)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/mutmut/__main__.py", line 424, in parse_run_argument
    update_line_numbers(filename)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/mutmut/cache.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "<string>", line 2, in update_line_numbers
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/pony/orm/core.py", line 519, in new_func
    result = func(*args, **kwargs)
  File "/Users/jwr003/coding/mutmut/venv/lib/python3.9/site-packages/mutmut/cache.py", line 364, in update_line_numbers
    existing_lines = [x.strip('\n') for x in f.readlines()]
  File "/Users/jwr003/.pyenv/versions/3.9.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4696: invalid start byte
```

**Comment by jeffwright13** [comment]
Well so it turns out that if I explicitly declare the file to run against with the `--paths-to-mutate` flag, it runs. it took a lot of experimentation to get there, though.

Example:
`mutmut run --paths-to-mutate ./tests/test_counters.py`

```
- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests need to be expanded.
🔇 Skipped.          Skipped.

1. Using cached time for baseline tests, to run baseline again delete the cache file

2. Checking mutants
⠼ 62/84  🎉 53  ⏰ 0  🤔 0  🙁 9  🔇 0
```

**Comment by boxed** [comment]
That looks wrong. You don't mutate the tests, you mutate the source code of your library/app.

**Comment by jeffwright13** [comment]
Like this?

```
$ tree -I venv -I build -I counters.egg-info -I dist
.
├── README.md
├── RELEASE_INSTRUCTIONS
├── counters
│   ├── __init__.py
│   ├── counters.py
│   └── manual_test.py
├── pytest.ini
├── setup.py
└── tests
    ├── __init__.py
    ├── conftest.py
    └── test_counters.py

2 directories, 10 files
(counters)
~/coding/counters on  main ⌚ 21:21:05
$ mutmut run --paths-to-mutate counters/counters.py

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests need to be expanded.
🔇 Skipped.          Skipped.

1. Using cached time for baseline tests, to run baseline again delete the cache file

2. Checking mutants
⠴ 38/38  🎉 32  ⏰ 0  🤔 0  🙁 6  🔇 0
```

**Comment by boxed** [comment]
Yea that looks more reasonable

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.
