### ISSUE TITLE
AttributeError when using --use-coverage

### ISSUE THREAD

**Issue by falcorocks** [boxed/mutmut#178]
```
pip install pytest pytest-cov mutmut hypothesis

(...)

Installing collected packages: iniconfig, toml, pluggy, more-itertools, py, attrs, pytest, coverage, pytest-cov, glob2, parso, click, pony, junit-xml, mutmut, sortedcontainers, hypothesis
Successfully installed attrs-19.3.0 click-7.1.2 coverage-5.2.1 glob2-0.7 hypothesis-5.23.11 iniconfig-1.0.1 junit-xml-1.8 more-itertools-8.4.0 mutmut-2.0.0 parso-0.8.0 pluggy-0.13.1 pony-0.7.13 py-1.9.0 pytest-6.0.1 pytest-cov-2.10.0 sortedcontainers-2.2.2 toml-0.10.1

pytest --cov=$MODULE tests/

(... pytest does its tests ok...)

mutmut run --paths-to-mutate=$MODULE --tests-dir=tests --use-coverage

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Results are stored in .mutmut-cache.
Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants.   The goal is for everything to end up in this bucket.
⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious.       Tests took a long time, but not long enough to be fatal.
🙁 Survived.         This means your tests needs to be expanded.
🔇 Skipped.          Skipped.

mutmut cache is out of date, clearing it...
1. Running tests without mutations

⠋ Running...
⠙ Running...
⠹ Running...
⠸ Running...
⠼ Running...
⠴ Running...
⠦ Running...
⠧ Running...
⠇ Running...
⠏ Running...
⠋ Running...
⠙ Running...Done
Traceback (most recent call last):
  File "/usr/local/bin/mutmut", line 8, in <module>
    sys.exit(climain())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mutmut/__init__.py", line 847, in wrapper
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mutmut/__main__.py", line 134, in climain
    sys.exit(main(command, argument, argument2, paths_to_mutate, backup, runner,
  File "/usr/local/lib/python3.8/site-packages/mutmut/__main__.py", line 264, in main
    check_coverage_data_filepaths(coverage_data)
  File "/usr/local/lib/python3.8/site-packages/mutmut/__init__.py", line 929, in check_coverage_data_filepaths
    for filepath in coverage_data._lines:
AttributeError: 'CoverageData' object has no attribute '_lines'
```

**Comment by falcorocks** [comment]
btw @boxed I am a big admirer of this work and I'm actively promoting :)

**Comment by falcorocks** [comment]
If I roll back to `coverage==4.4` from `5.2.1` everything works fine

**Comment by boxed** [comment]
The fix is on master (https://github.com/boxed/mutmut/commit/ef3c176999b12e129244f71e6b29178afa34d8a9).

Could you try it?

If you confirm it works I can roll a release so no one else trips on this.

**Comment by falcorocks** [comment]
Woah, that was fast! I'm happy to help with confirming, but I'm used to downloading from pip, so I'm not sure how to download from source. Can you guide me?

**Comment by atugushev** [comment]
@falcorocks 

```console
$ pip install git+https://github.com/boxed/mutmut.git
```

**Comment by falcorocks** [comment]
I can confirm it works

**Comment by boxed** [comment]
Nice. I have now rolled a release.
