### ISSUE TITLE
AttributeError in argument_mutation

### ISSUE THREAD

**Issue by federicobond** [boxed/mutmut#19]
###### Traceback
```
Running tests without mutations... Done
Traceback (most recent call last):
  File "env/bin/mutmut", line 5, in <module>
    main()
  File "env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "env/lib/python3.6/site-packages/mutmut/__main__.py", line 56, in wrapper
    f(*args, **kwargs)
  File "env/lib/python3.6/site-packages/mutmut/__main__.py", line 317, in main
    add_mutations_by_file(mutations_by_file, filename, _exclude, dict_synonyms)
  File "env/lib/python3.6/site-packages/mutmut/__main__.py", line 519, in add_mutations_by_file
    dict_synonyms=dict_synonyms,
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 363, in list_mutations
    mutate(context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 273, in mutate
    mutate_list_of_nodes(result, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 301, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 342, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 320, in mutate_node
    children=getattr(i, 'children', None),
  File "env/lib/python3.6/site-packages/tri/declarative/__init__.py", line 340, in evaluate
    return func_or_value(**kwargs)
  File "env/lib/python3.6/site-packages/mutmut/__init__.py", line 91, in argument_mutation
    children[0] = Name(c.value + 'XX', start_pos=c.start_pos, prefix=c.prefix)
AttributeError: 'PythonNode' object has no attribute 'value'
```
###### Value of `c`:
```
PythonNode(atom, [<Operator: (>, PythonNode(testlist_comp, [PythonNode(atom_expr, [<Name: key@145,24>, PythonNode(trailer, [<Operator: (>, <Name: field@145,28>, <Operator: )>])]), <Operator: ,>, <Keyword: True>]), <Operator: )>])
```

**Comment by federicobond** [comment]
Source looks like this:
```
key = lambda a: "foo"  
filters = dict((key(field), False) for field in fields) 
```

**Comment by boxed** [comment]
I think I've solved this before, because when I wrote a test for this it passed. Can you update to the latest version of the master branch and try again?

**Comment by boxed** [comment]
Huh. Well the test I added broke on Travis but passed on my machine. Strange. I’ll have to look at that.

**Comment by boxed** [comment]
I must have been confused and ran the wrong test or something... in any case the fix was trivial and I've pushed the fix. Thanks for the bug report!
