### ISSUE TITLE
`IndexError` inside `expression_mutation`

### ISSUE THREAD

**Issue by sobolevn** [boxed/mutmut#26]
Hi, thanks for this module! I am trying to use it with my app: https://github.com/wemake-services/wemake-python-styleguide

But, it is failing. Output:

```
» mutmut 
Running tests without mutations... Done
Traceback (most recent call last):
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/bin/mutmut", line 5, in <module>
    main()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__main__.py", line 55, in wrapper
    f(*args, **kwargs)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__main__.py", line 225, in main
    add_mutations_by_file(mutations_by_file, filename, _exclude, dict_synonyms)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__main__.py", line 417, in add_mutations_by_file
    dict_synonyms=dict_synonyms,
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 373, in list_mutations
    mutate(context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 286, in mutate
    mutate_list_of_nodes(result, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 352, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 311, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 352, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 311, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 352, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 311, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 352, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 311, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 352, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 311, in mutate_node
    mutate_list_of_nodes(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 352, in mutate_list_of_nodes
    mutate_node(i, context=context)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 330, in mutate_node
    children=getattr(i, 'children', None),
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/tri/declarative/__init__.py", line 341, in evaluate
    return func_or_value(**kwargs)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.6/site-packages/mutmut/__init__.py", line 184, in expression_mutation
    if children[2].value == '=':
IndexError: list index out of range
```

## Versions

```
» pip freeze
Could not find setup.py for directory /Users/sobolev/Documents/github/wemake-python-styleguide (tried all parent directories)
added-value==0.8
alabaster==0.7.12
atomicwrites==1.2.1
attrs==18.2.0
Babel==2.6.0
bandit==1.5.1
certifi==2018.10.15
chardet==3.0.4
Click==7.0
coverage==4.5.1
dataclasses==0.6
doc8==0.8.0
docutils==0.14
eradicate==0.2.1
flake8==3.6.0
flake8-bandit==1.0.2
flake8-broken-line==0.1.0
flake8-bugbear==18.8.0
flake8-builtins==1.4.1
flake8-coding==1.3.1
flake8-commas==2.0.0
flake8-comprehensions==1.4.1
flake8-debugger==3.1.0
flake8-docstrings==1.3.0
flake8-eradicate==0.1.1
flake8-isort==2.5
flake8-logging-format==0.5.0
flake8-pep3101==1.2.1
flake8-polyfill==1.0.2
flake8-print==3.1.0
flake8-pytest==1.3
flake8-quotes==1.0.0
flake8-string-format==0.2.3
flake8-type-annotations==0.1.0
gitdb2==2.0.5
GitPython==2.1.11
glob2==0.6
idna==2.7
imagesize==1.1.0
isort==4.3.4
Jinja2==2.10
m2r==0.2.1
MarkupSafe==1.0
mccabe==0.6.1
mistune==0.8.4
more-itertools==4.3.0
mutmut==0.0.22
mypy==0.641
mypy-extensions==0.4.1
packaging==18.0
parso==0.3.1
pbr==5.1.0
pep8-naming==0.7.0
pluggy==0.8.0
pockets==0.7.2
py==1.7.0
pycodestyle==2.4.0
pydocstyle==3.0.0
pyflakes==2.0.0
Pygments==2.2.0
Pympler==0.6
pyparsing==2.2.2
pytest==3.9.3
pytest-cov==2.6.0
pytest-flake8==1.0.2
pytest-isort==0.2.1
pytest-randomly==1.2.3
pytz==2018.7
PyYAML==3.13
requests==2.20.0
restructuredtext-lint==1.1.3
six==1.11.0
smmap2==2.0.5
snowballstemmer==1.2.1
Sphinx==1.8.1
sphinx-autodoc-typehints==1.3.0
sphinx-readable-theme==1.3.0
sphinxcontrib-napoleon==0.7
sphinxcontrib-websupport==1.1.0
stevedore==1.30.0
testfixtures==6.3.0
tomlkit==0.4.6
tri.declarative==1.0.6
tri.struct==2.5.6
typed-ast==1.1.0
typing==3.6.6
typing-extensions==3.6.6
urllib3==1.24
-e git+https://github.com/wemake-services/wemake-python-styleguide.git@8b9cfd896ae500e99a5a47a5f10386150a26082c#egg=wemake_python_styleguide
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I am using:
- `python3.6`
- `poetry@12`

## Configuration

I have added these values to my `setup.cfg`:

```
[mutmut]
paths_to_mutate = wemake_python_styleguide/
backup = False
runner = pytest
tests_dir = tests/
```

Any ideas?

**Comment by boxed** [comment]
The first thing to cross my mind is that the crash is handled badly: it should have printed the file, line number (and preferably column) of the parse error. That's bug one. The other problem is probably trivial to understand and turn into a small unit test after that. 

If you want to give it a shot the context variable should contain sufficient information for most of that data.

I'll try to look at it as soon as I can but I don't know when that will be.

**Comment by boxed** [comment]
The dependency tree for poetry plus your project is pretty large I must say. Just installing into a venv is taking a long time!

**Comment by boxed** [comment]
Well, it was trivial to fix the error output and the bug when I got everything up and running. 

I have rolled a new release that fixes your problem. Your test suite is pretty slow, so I would be interested to see if you can have a use for pytest-testmon and if it makes mutation testing faster.

**Comment by boxed** [comment]
Oh yea, and you might also want to try using the "features" branch of pytest for a while, there are some optimizations there that might be relevant. Or just use 3.6.0 which is the fastest in my measurements.

**Comment by sobolevn** [comment]
@boxed thanks! Works now. But, yes. That's too slow.

I guess `pytest -x --no:flake8 --no:isort --no:cov` will make it faster.
Currently measuring the regular execution time.

**Comment by sobolevn** [comment]
`pytest -x -o addopts=""` gives an awesome `19` seconds per loop.
Thanks again @boxed!
