### ISSUE TITLE
UTF-8 BOM in setup.py

### ISSUE THREAD

**Issue by l0b0** [boxed/mutmut#276]
Mirror of https://github.com/nix-community/poetry2nix/pull/1085 - Would it be possible to remove it here to avoid confusing downstream consumers like https://docs.python.org/3/library/ast.html?

**Comment by boxed** [comment]
I don't understand what you are saying. If python understands the BOM fine, what is the problem?

And surely you made some mistake calling `ast` downstream?

**Comment by l0b0** [comment]
I'm not familiar with the entire call stack, but [here's the error message](https://github.com/nix-community/poetry2nix/issues/1084):

```text
Traceback (most recent call last):
  File "/nix/store/nry474aicns0vk6f1y76via6g1snj8ms-python-requires-patch-hook.py", line 70, >
    tree = ast.parse(f.read())
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/ast.py", l>
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    ﻿#!/usr/bin/env python3
    ^
SyntaxError: invalid non-printable character U+FEFF
```

Given that looks like the official Python 3.10 AST library, presumably it's at least rather risky having a UTF-8 BOM in this file. And unless the BOM serves some special purpose (Python 3 code is assumed to be UTF-8 across the board, after all), it might be better to remove it.

Cc @adisbladis and @cpcloud, who are much more active in the relevant project.

**Comment by boxed** [comment]
Weird. Because:

```pycon
>>> with open('setup.py', 'br') as f:
...     foo = f.read()
... 
>>> import ast
>>> ast.parse(foo)
<ast.Module object at 0x101299a90>
>>> foo[:10]
b'\xef\xbb\xbf#!/usr/'
```

Python 3.9, 3.10, and 3.11. 

So.. I don't understand why this us behaving differently for you..

**Comment by boxed** [comment]
hmm.. actually... that's a bit weird that you can't do that imo.

**Comment by DudeNr33** [comment]
Have you tried explicitly specifying the encoding? 
```python
with open("setup.py", encoding="utf-8") as f:
```

https://peps.python.org/pep-0597/
