### ISSUE TITLE
IndexError: tuple index out of range when running `mutmut results`

### ISSUE THREAD

**Issue by aladopoulos** [boxed/mutmut#282]
After a successful `mutmut run` for a combination of specific test file and source file  I am doing `mutmut results` and I get the following:

```
Traceback (most recent call last):
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/bin/mutmut", line 8, in <module>
    sys.exit(climain())
             ^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/mutmut/__main__.py", line 152, in results
    print_result_cache()
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/mutmut/cache.py", line 88, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in print_result_cache
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/pony/orm/core.py", line 519, in new_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/mutmut/cache.py", line 183, in print_result_cache
    print_stuff('Timed out ⏰', select(x for x in Mutant if x.status == BAD_TIMEOUT))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/pony/orm/core.py", line 5560, in select
    return make_query(args, frame_depth=cut_traceback_depth+1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/pony/orm/core.py", line 5546, in make_query
    tree, external_names, cells = decompile(gen)
                                  ^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/pony/orm/decompiling.py", line 38, in decompile
    decompiler = Decompiler(codeobject)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/pony/orm/decompiling.py", line 154, in __init__
    decompiler.get_instructions()
  File "/Users/aladopoulos/.pyenv/versions/3.11.3/envs/so-3.11/lib/python3.11/site-packages/pony/orm/decompiling.py", line 196, in get_instructions
    arg = [code.co_names[oparg]]
           ~~~~~~~~~~~~~^^^^^^^
IndexError: tuple index out of range
``` 

Do you think there is something wrong with my local setup? I haven't encountered this issue in the past.

I can see individual mutants with `mutmut show <id>`.

Let me know if you need any more information and thanks so much in advance.

**Comment by Daniel-I-Am** [comment]
I was just looking for an issue with the exact same problem, seems you beat me to the creation. I did some further looking and it seems to be in the pony ORM library. See https://github.com/ponyorm/pony/issues/668#issuecomment-1321885007

**Comment by aladopoulos** [comment]
@Daniel-I-Am thanks so much for pointing to the core of this issue. Should I close this one?

**Comment by Daniel-I-Am** [comment]
I don't think there's anything that can be fixed within mutmut itself without a change of library or something like it. At least now there's an issue with the underlying reason documented. Probably best to not leave it lingering here :slightly_smiling_face: 

You might want to thumbs-up the issue on pony ORM to show your interest in getting this resolved.
