### ISSUE TITLE
Pony throws IndexError on results command

### ISSUE THREAD

**Issue by barraquito** [boxed/mutmut#295]
After knowing about `mutmut` on a talk I tried to use it in a small project I have (using Python 3.12). I use `poetry` (version 1.6.1) to manage dependencies and running commands on that project. I have the following packages:

```
click              8.1.7     Composable command line interface toolkit
glob2              0.7       Version of the glob module that can capture patterns and supports recursive wildcards
junit-xml          1.9       Creates JUnit XML test result documents that can be read by tools such as Jenkins
mutmut             2.4.4     mutation testing for Python 3
parso              0.8.3     A Python Parser
pony               0.7.17    Pony Object-Relational Mapper
toml               0.10.2    Python Library for Tom's Obvious, Minimal Language

```

Everything goes fine running `mutmut`:

```
$ poetry run mutmut run --paths-to-mutate "src/" --tests-dir "tests/"
```

But I get an error trying to get the results:

```
$ poetry run mutmut results            
To apply a mutant on disk:
    mutmut apply <id>

To show a mutant:
    mutmut show <id>

Traceback (most recent call last):
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/bin/mutmut", line 8, in <module>
    sys.exit(climain())
             ^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/mutmut/__main__.py", line 152, in results
    print_result_cache()
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/mutmut/cache.py", line 88, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in print_result_cache
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/pony/orm/core.py", line 519, in new_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/mutmut/cache.py", line 183, in print_result_cache
    print_stuff('Timed out ⏰', select(x for x in Mutant if x.status == BAD_TIMEOUT))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/pony/orm/core.py", line 5560, in select
    return make_query(args, frame_depth=cut_traceback_depth+1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/pony/orm/core.py", line 5546, in make_query
    tree, external_names, cells = decompile(gen)
                                  ^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/pony/orm/decompiling.py", line 43, in decompile
    decompiler = Decompiler(codeobject)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/pony/orm/decompiling.py", line 160, in __init__
    decompiler.get_instructions()
  File "/home/sergio/.cache/pypoetry/virtualenvs/titsa-bot-RylRNGSl-py3.12/lib/python3.12/site-packages/pony/orm/decompiling.py", line 216, in get_instructions
    arg = [cmp_op[oparg]]
           ~~~~~~^^^^^^^
IndexError: tuple index out of range
```

I get more or less the same output if I try to get the IDs of a specific mutant classes (i.e. killed):

```
$ poetry run mutmut result-ids killed
```

I've tried to find similar issues on the repo or in the internet, but the only one I found was [an unanswered question on StackOverflow](https://stackoverflow.com/questions/76253668/wht-python-package-mutmut-doesnt-work-with-and-command-mutmut-results-retur). Also tried to remove mutmut cache file and do everything again, but I get the same.

Is the error because my environment, anyone else has had the same issue or it's a totally new issue?

**Comment by boxed** [comment]
Could you try with python 3.10?

**Comment by barraquito** [comment]
It worked! Thank you so much, for your help. I should tried that before.
