### ISSUE TITLE
--use-coverage: No such file or directory: '.coverage'

### ISSUE THREAD

**Issue by blueyed** [boxed/mutmut#34]
With pytest:
```
% mutmut --use-coverage --runner 'python -m pytest testing/test_collection.py' src/_pytest/nodes.py
Running tests without mutations... Done
Using coverage data from .coverage file
Traceback (most recent call last):
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/coverage/data.py", line 292, in read_file
    with self._open_for_reading(filename) as f:
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/coverage/data.py", line 306, in _open_for_reading
    return open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: '.coverage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/Vcs/pytest/.venv/bin/mutmut", line 5, in <module>
    main()
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/mutmut/__main__.py", line 55, in wrapper
    f(*args, **kwargs)
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/mutmut/__main__.py", line 215, in main
    coverage_data = read_coverage_data(use_coverage)
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/mutmut/__main__.py", line 402, in read_coverage_data
    coverage_data.read_file('.coverage')
  File "…/Vcs/pytest/.venv/lib/python3.6/site-packages/coverage/data.py", line 297, in read_file
    filename, exc.__class__.__name__, exc,
coverage.misc.CoverageException: Couldn't read data from '.coverage': FileNotFoundError: [Errno 2] No such file or directory: '.coverage'
```

**Comment by boxed** [comment]
Yea, you have to supply the coverage data yourself. Should have a good error message explaining this.
