### ISSUE TITLE
error: BadTestExecutionCommandsException

### ISSUE THREAD

**Issue by adam-moss** [boxed/mutmut#340]
Hi,

I'm trying to introduce `mutmut` into an existing project but am failing to get it to run with:

```console
.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 694, in execute_pytest
    raise BadTestExecutionCommandsException(params)
mutmut.__main__.BadTestExecutionCommandsException: ['--doctest-glob=*.md', '--doctest-modules', '--ignore=mutants', '--random-order', '--strict-config', '--strict-markers', '-x', '-q', '--import-mode=append']
```

I first had to modify the pytest.ini to include `--ignore mutants` to get pytest itself happy, but I still can't get `mutmut` to play ball.

```ini
[pytest]
addopts = --doctest-glob="*.md" --doctest-modules --ignore=mutants --random-order --strict-config --strict-markers
empty_parameter_set_mark = xfail
xfail_strict=true
```

Any suggestions greatly received.

Thanks!

**Comment by boxed** [comment]
What is the command line command you are using to run mutmut? It looks like you are passing params to `mutmut run` which it does not accept.

**Comment by boxed** [comment]
Hmm.. I wonder what goes on here. Could you give me the full log? Is this crash from the stats phase, clean tests phase...?

Can you run `python -m pytest` inside the `mutants` folder?

**Comment by adam-moss** [comment]
Thanks for the replies.

In terms of command I'm doing `poetry run mutmut run` and the log I'm getting is as follows:

```console
~/Projects/**redact** (test/mutmut *$%|u=) % poetry run mutmut run
generating mutants
    done in 12066ms
⠦ running stats
Traceback (most recent call last):
  File "/Users/adam-moss/Projects/**redact**/.venv/bin/mutmut", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 1170, in run
    collect_or_load_stats(runner)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 1016, in collect_or_load_stats
    run_stats_collection(runner)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 994, in run_stats_collection
    collect_stats_exit_code = runner.run_stats(tests=tests)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 711, in run_stats
    return int(self.execute_pytest(['-x', '-q', '--import-mode=append'] + list(tests), plugins=[stats_collector]))
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 694, in execute_pytest
    raise BadTestExecutionCommandsException(params)
mutmut.__main__.BadTestExecutionCommandsException: ['--doctest-glob=*.md', '--doctest-modules', '--ignore=mutants', '--random-order', '--strict-config', '--strict-markers', '-x', '-q', '--import-mode=append']
```

Thanks!

**Comment by boxed** [comment]
What happens when you run `poetry run pytest --doctest-glob=*.md --doctest-modules --ignore=mutants --random-order --strict-config --strict-markers -x -q --import-mode=append` ?

**Comment by adam-moss** [comment]
In the root of the project dir it fails with

```console
ImportError while loading conftest '/Users/adam.moss/Projects/**redact/tests/conftest.py'.
ModuleNotFoundError: No module named 'tests.conftest'
```

If I remove the `--import-mode=append` it works as expect, tests run and pass.

If I run when in the `mutants` directory I get the same error with `--import-mode=append` as above, without it `pytest` _fails_ to run with:

```console
______________ ERROR collecting mutants/src/**redact**/__about__.py _______________
import file mismatch:
imported module '**redact**.__about__' has this __file__ attribute:
  /Users/adam.moss/Projects/**redact**/src/**redact**/__about__.py
which is not the same as the test file we want to collect:
  /Users/adam.moss/Projects/**redact**/mutants/src/**redact**/__about__.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR src/**redact**/__about__.py
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
1 error in 0.14s
```

Removing all `*.pyc` files doesn't make a difference.

**Comment by boxed** [comment]
Could you try again with the latest code that is on `main` now? I have made some improvements to this.

**Comment by adam-moss** [comment]
Using the latest on main if I run `poetry run mutmut run` from the project root I get

```console
% poetry run mutmut run
⠹ Generating mutants
    done in 529ms
⠏ Running stats     
Traceback (most recent call last):
  File "/Users/adam-moss/Projects/**redact**/.venv/bin/mutmut", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 1225, in run
    collect_or_load_stats(runner)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 1055, in collect_or_load_stats
    run_stats_collection(runner)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 1033, in run_stats_collection
    collect_stats_exit_code = runner.run_stats(tests=tests)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 720, in run_stats
    return int(self.execute_pytest(['-x', '-q', '--import-mode=append'] + list(tests), plugins=[stats_collector]))
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 701, in execute_pytest
    raise BadTestExecutionCommandsException(params)
mutmut.__main__.BadTestExecutionCommandsException: ['--doctest-glob=*.md', '--doctest-modules', '--ignore=mutants', '--random-order', '--strict-config', '--strict-markers', '-x', '-q', '--import-mode=append', '--rootdir=.']
```

If I run from within the `mutants` directory I get:

```console
% cd mutants 
% poetry run mutmut run
⠹ Generating mutants
Traceback (most recent call last):
  File "/Users/adam-moss/Projects/**redact**/.venv/bin/mutmut", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 1203, in run
    create_mutants()
    ~~~~~~~~~~~~~~^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 215, in create_mutants
    create_mutants_for_file(path, output_path)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 251, in create_mutants_for_file
    mutant_names, hash_by_function_name = write_all_mutants_to_file(out=out, source=source, filename=filename)
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 295, in write_all_mutants_to_file
    for type_, x, name_and_hash, mutant_name in yield_mutants_for_module(ast, no_mutate_lines):
                                                ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 571, in yield_mutants_for_module
    yield from yield_mutants_for_class(child_node, no_mutate_lines=no_mutate_lines)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 527, in yield_mutants_for_class
    yield from yield_mutants_for_class_body(child_node, no_mutate_lines=no_mutate_lines)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 538, in yield_mutants_for_class_body
    yield from yield_mutants_for_function(child_node, class_name=class_name, no_mutate_lines=no_mutate_lines)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 493, in yield_mutants_for_function
    with rename_function_node(node, suffix='orig', class_name=class_name):
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam-moss/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 342, in rename_function_node
    mangled_name = mangle_function_name(name=orig_name, class_name=class_name)
  File "/Users/adam-moss/Projects/**redact**/.venv/lib/python3.13/site-packages/mutmut/__main__.py", line 781, in mangle_function_name
    assert CLASS_NAME_SEPARATOR not in name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

As before `poetry run pytest` works from the project root but fails within the `mutants` folder.

**Comment by boxed** [comment]
Maybe you could try to reproduce this on a smaller repo that you can share? Doing it back and forth like this isn't going so well...

**Comment by adam-moss** [comment]
Initial repo https://github.com/adam-moss/mutmut-issue-340

**Comment by StevenAngel-ai** [comment]
I also have this issue, and when running with debug = True, I get the following output:

```
 Running stats     python -m pytest  -vv -x -q --import-mode=append --rootdir=.
ImportError while loading conftest '/Users/sangel/Code/autobot/components/conftest.py'.
conftest.py:54: in <module>
    from test_infrastructure.mocks import firestore_mock
test_infrastructure/mocks/firestore_mock.py:57: in <module>
    from common import firestore_tools
common/firestore_tools.py:53: in <module>
    from common import config
common/config.py:48: in <module>
    from common.getenv import getenv
common/getenv.py:50: in <module>
    from common.cache import cache
common/cache.py:65: in <module>
    from common.tools import getenv_no_cache
common/tools.py:3718: in <module>
    def x_generate_random_id__mutmut_2(size: int = 4, chars: str = string.ascii_uppercase - string.digits):
E   TypeError: unsupported operand type(s) for -: 'str' and 'str'
    exit code 4

Traceback (most recent call last):
  File "/Users/sangel/Code/autobot/.venv/bin/mutmut", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/mutmut/__main__.py", line 1238, in run
    collect_or_load_stats(runner)
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/mutmut/__main__.py", line 1064, in collect_or_load_stats
    run_stats_collection(runner)
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/mutmut/__main__.py", line 1042, in run_stats_collection
    collect_stats_exit_code = runner.run_stats(tests=tests)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/mutmut/__main__.py", line 724, in run_stats
    return int(self.execute_pytest(['-x', '-q', '--import-mode=append'] + list(tests), plugins=[stats_collector]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangel/Code/autobot/.venv/lib/python3.12/site-packages/mutmut/__main__.py", line 705, in execute_pytest
    raise BadTestExecutionCommandsException(params)
mutmut.__main__.BadTestExecutionCommandsException: ['-ra', '--color=yes', '--disable-socket', '--allow-unix-socket', '-vv', '-x', '-q', '--import-mode=append', '--rootdir=.']
```

My current theory is that `--import-mode=append` is just not right for the repo. Given that I have `--import-mode=importlib` in my pytest.ini for normal test running. And when I run pytest with the option `--import-mode=append`, it also errors out. 

```
import file mismatch:
imported module 'service_test' has this __file__ attribute:
  /Users/sangel/Code/autobot/components/admin_svc/service_test.py
which is not the same as the test file we want to collect:
  /Users/sangel/Code/autobot/components/batch_query_svc/service_test.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

Because this repo has multiple services, which each have a service_test.py. And per the docs for pytest, with `prepend` and `append`, all your test files must have unique names. https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html

Can we just either let mutmut pick up the import mode from the pytest.ini or default it to `importlib` instead of `append`?

**Comment by boxed** [comment]
@StevenAngel-ai You have an entirely different issue. Can you please post a new issue for this and remove your comment from this issue?

**Comment by Otto-AA** [comment]
This works now, I think it was the same fix as for #345 .

```
⠦ Generating mutants
    done in 172ms
⠼ Listing all tests 
⠙ Running clean tests
    done
⠧ Running forced fail test
    done
Running mutation testing
⠦ 38/38  🎉 11 🫥 0  ⏰ 0  🤔 0  🙁 27  🔇 0
62.78 mutations/second
```
