### ISSUE TITLE
Running with --use-coverage fails

### ISSUE THREAD

**Issue by miketheman** [boxed/mutmut#63]
Hello! I am trying out mutmut today, having tried out cosmic-ray recently, and mutmut appears to be a simpler implementation, so thanks for making this!

My project uses pytest, and leverages coverage, and during my initial mutmut run, it found mutants in a function that I have a `pragma: no cover` set, so I wanted to use the flag to leverage only covered lines for mutation (there's also a couple of private methods that aren't exercised).

When invoking:

    mutmut run --use-coverage --paths-to-mutate unsilencer.py

I get this traceback:

```pycon
1. Using cached time for baseline tests, to run baseline again delete the cache file
Using coverage data from .coverage file
Traceback (most recent call last):
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/bin/mutmut", line 5, in <module>
    main()
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/lib/python3.7/site-packages/mutmut/__main__.py", line 59, in wrapper
    f(*args, **kwargs)
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/lib/python3.7/site-packages/mutmut/__main__.py", line 285, in main
    coverage_data = read_coverage_data(use_coverage)
  File "/Users/miketheman/.local/share/virtualenvs/unsilencer-YmPJJ04A/lib/python3.7/site-packages/mutmut/__main__.py", line 484, in read_coverage_data
    coverage_data.read_file('.coverage')
AttributeError: 'CoverageSqliteData' object has no attribute 'read_file'
```

Reference:

https://github.com/boxed/mutmut/blob/a3c5efa63cc5c6bd515317e361d2199d03b2a2db/mutmut/__main__.py#L482-L484

It appears that the `read_file` may have been removed upstream? I'm using `pytest-cov` which installs anything above 4.4, and using 5.0a4 the method is removed.

Manually back-tracking to coverage 4.5.2 (latest stable) provides a non-traceback execution, however it doesn't appear to respect the coverage rules, as it's mutating a `no cover` line, like so:

```diff
$ mutmut show 26
--- unsilencer.py
+++ unsilencer.py
@@ -77,7 +77,7 @@
             remove_from_list(suppression_list, email_address)


-if __name__ == "__main__":  # pragma: no cover
+if __name__ == "XX__main__XX":  # pragma: no cover
     try:
         input = sys.argv[1]
     except IndexError:
```

is this the desired behavior? I couldn't find any reference to coverage in the test/s directory, hoping to see how this is meant to work. Let me know if there's anything else I can do to help!

**Comment by boxed** [comment]
Ah, didn't know we fail on the newer version of coverage with SQLite database, that's important information, we need to look at that for sure! 

As for if this is expected behavior, no, this seems like a bug. Sounds like we don't handle skipped/ignored the same as not covered. Looking at it now it looks like we need to use the `coverage.parser.PythonParser` class to get those. That's unfortunate.

**Comment by nklapste** [comment]
I found that replacing:
```python
import coverage
coverage_data = coverage.CoverageData()
coverage_data.read_file('.coverage')
return coverage_data
```
with this:
```python
from coverage import Coverage
coverage_data = Coverage(".coverage").get_data()
return coverage_data 
```
this should conform with the modern api of `coverage`.

See https://github.com/nklapste/mutmut/pull/6/commits/8d8bb2a8167d98122a452ee476f9325dc9029c5a for example.

**Comment by boxed** [comment]
Awesome!

**Comment by boxed** [comment]
I'm assuming this is fixed with the above mentioned merged PR. If it isn't please reopen!
