### ISSUE TITLE
Error on run with empty source

### ISSUE THREAD

**Issue by kolotaev** [boxed/mutmut#77]
Hi,

I've got a problem when running mutmut v1.3.0. `IndexError: string index out of range`.
Full stack trace:
```
1. Using cached time for baseline tests, to run baseline again delete the cache file
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mutmut/__main__.py", line 675, in <module>
    climain()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mutmut/__main__.py", line 66, in wrapper
    f(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mutmut/__main__.py", line 204, in climain
    version, suspicious_policy, untested_policy))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mutmut/__main__.py", line 331, in main
    add_mutations_by_file(mutations_by_file, filename, _exclude, dict_synonyms)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mutmut/__main__.py", line 595, in add_mutations_by_file
    dict_synonyms=dict_synonyms,
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mutmut/__init__.py", line 417, in __init__
    if source is not None and source[-1] != '\n':
IndexError: string index out of range
```

I've tried it on [this](https://github.com/kolotaev/vakt/tree/attribute-checker) codebase by running `python3 -m mutmut run --runner="python3 -m pytest" --paths-to-mutate="vakt/" --dict-synonyms="Struct, NamedStruct"`.
Seems this is caused by empty `__init__.py`  files.

Possible fix:
in mutmut/__ init __.py do 
```python
class Context(object):
    def __init__(self, source=None, mutation_id=ALL, dict_synonyms=None, filename=None, exclude=lambda context: False, config=None):
        self.index = 0
        self.remove_newline_at_end = False
        if source is not None and source != '' and source[-1] != '\n':
            source += '\n'
```

**Comment by boxed** [comment]
Thanks for this bug report. Yes, the problem is pretty obvious once you see it. I'll fix it as soon as I'm in front of a suitible computer.

**Comment by boxed** [comment]
Fixed. A release will be on pypi in ~10 minutes when the tests are complete.

**Comment by kolotaev** [comment]
👍
