### ISSUE TITLE
Can't run mutmut

### ISSUE THREAD

**Issue by JamieYnonan** [boxed/mutmut#80]
I have this error.

command:
`mutmut run --paths-to-mutate=$PROJECT --tests-dir=$TESTS_DIR`

```
Traceback (most recent call last):
  File "/usr/local/bin/mutmut", line 5, in <module>
    climain()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 695, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 654, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.5/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: a bytes-like object is required, not 'str'


```

Docker:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

```
Docker Image:
`amazonlinux:2017.09`

requirements.txt:
```
...
mutmut==1.3.1
pytest==4.2.0
```

**Comment by boxed** [comment]
Strange. That looks like this bug in click: https://github.com/pallets/click/issues/494 but it's supposed to be fixed in 2016. What version of click did you end up with?

**Comment by JamieYnonan** [comment]
Thanks @boxed , I updated the click's version (from 6.0 to 7.0) and now I have this error:

```
mutmut cache is out of date, clearing it...
1. Running tests without mutations
⠋ Running...Traceback (most recent call last):
  File "/usr/local/bin/mutmut", line 5, in <module>
    climain()
  File "/usr/local/lib64/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mutmut/__main__.py", line 66, in wrapper
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mutmut/__main__.py", line 204, in climain
    version, suspicious_policy, untested_policy))
  File "/usr/local/lib/python3.5/site-packages/mutmut/__main__.py", line 295, in main
    using_testmon=using_testmon
  File "/usr/local/lib/python3.5/site-packages/mutmut/__main__.py", line 579, in time_test_suite
    raise RuntimeError("Tests don't run cleanly without mutations. Test command was: %s\n\nOutput:\n\n%s" % (test_command, '\n'.join(output)))
RuntimeError: Tests don't run cleanly without mutations. Test command was: python -m pytest -x

Output:

/usr/bin/python: No module named pytest

```

`pip-3.5 install -r requirements.txt`

```
...
mutmut==1.3.1
pytest==4.2.0
click==7.0
coverage==4.5.1
```

**Comment by boxed** [comment]
Mutmut guesses you use pytest for tests since that's by far the most popular (and best) test runner. It seems you don't. You need to set the test runner command in setup.cfg as per the Readme.

**Comment by JamieYnonan** [comment]
thanks @boxed , I had a class that gave me problems.

**Comment by boxed** [comment]
I'd recommend to put those settings in setup.cfg so you don't need to remember them and can just run mutmut run.
