### ISSUE TITLE
mutmut doesn't seem to work on windows

### ISSUE THREAD

**Issue by fmoor** [boxed/mutmut#9]
It would appear that there are hard coded paths that prevent mutmut from running on windows. Would the accepted solution [here](https://stackoverflow.com/questions/6735917/redirecting-stdout-to-nothing-in-python) be an acceptable fix?

```batch
>mutmut-cmd --tests-dir execution\tests execution                                                                                                                     Traceback (most recent call last):
File "C:\Users\fmoor\.venv\barometer\Scripts\mutmut-cmd.py", line 185, in <module>
    main()
File "c:\users\fmoor\.venv\barometer\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
File "c:\users\fmoor\.venv\barometer\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
File "c:\users\fmoor\.venv\barometer\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
File "c:\users\fmoor\.venv\barometer\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
File "c:\users\fmoor\.venv\barometer\lib\site-packages\mutmut\__init__.py", line 35, in wrapper
    f(*args, **kwargs)
File "C:\Users\fmoor\.venv\barometer\Scripts\mutmut-cmd.py", line 73, in main
    null_stdout = open('/dev/null', 'w') if not s else None
FileNotFoundError: [Errno 2] No such file or directory: '/dev/null'
```

Windows 10 Enterprise
Python 3.6.2 (v3.6.2:5fd33b5, Jul 8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
mutmut (0.0.3)

**Comment by boxed** [comment]
Thanks!
